### ISSUE TITLE
Customizing the Navbar by adding icons to links

### ISSUE THREAD

**Issue by swardhan** [firstcontributions/firstcontributions.github.io#10]
🐞 **Problem**
The header and navbar aren't very detailed in design terms.

🎯 **Goal**
Adding Icons beside the links to twitter, github and slack.

**Comment by svcastaneda** [comment]
I can pick this one up! ✨

**Comment by Roshanjossey** [comment]
Hi @svcastaneda, I'm thrilled to see someone working with GitHub here. I'd love to learn your feedback about this project and get all the help I can from you.

@swardhan has already started working on this issue. Could you please help to review those changes once a pull request is raised?

If you wanna work on something now, you could take up #13 too.

**Comment by isa3bel** [comment]
is this issue resolved?

**Comment by mohak852** [comment]
i have solved this issue and created a pull request kindly merge this pull request

**Comment by mohak852** [comment]
Any updates on my pull request

**Comment by sara-02** [comment]
@mohak852 Sorry I forgot to ask, can you please share a screenshot from your localhost with the updated changes.

**Comment by sara-02** [comment]
As in running the website locally and screenshot the new UI

**Comment by mohak852** [comment]
![Screenshot from 2020-05-24 02-46-14](https://user-images.githubusercontent.com/58987025/82734849-2786d300-9d3b-11ea-8d00-5c791d6d7c04.png)

**Comment by sara-02** [comment]
@mohak852 Since your PR is merged can we close this issue now? Or are there some aspects of this issue that you are still working on?

**Comment by mohak852** [comment]
Ya you can close this issue
