### ISSUE TITLE
Support for GitLab

### ISSUE THREAD

**Issue by oxr463** [firstcontributions/firstcontributions.github.io#102]
I would like to add projects that are hosted on GitLab, (not just [.com](https://gitlab.com), but also other instances as well, e.g. <https://code.ungleich.ch>).

Instead of `githubLink`, it could be `projectLink`. Not sure what all is needed to make this happen.

```js
const projectList = [
  {
    name: 'React',
    imageSrc: 'https://camo.githubusercontent.com/22045498095171997ccf6a9554672519b9f67898/68747470733a2f2f63646e2e776f726c64766563746f726c6f676f2e636f6d2f6c6f676f732f72656163742e737667',
    githubLink: 'https://github.com/facebook/react/contribute',
    description: 'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
    tags: ['JavaScript', 'UI', 'Web App'],
  },

[ . . . TRUNCATED . . . ]
```
Source: https://github.com/firstcontributions/firstcontributions.github.io/blob/source/src/components/ProjectList/listOfProjects.js

**Comment by NdibeRaymond** [comment]
i would like to take on this issue.

**Comment by NdibeRaymond** [comment]
any body has any idea on how to go about this?

**Comment by sara-02** [comment]
Hey @NdibeRaymond so there are 2 possible ways for now:
Change the variable `githublink` to `projectlink` in this file and and the files that render this page's info.
Or add the gitlab project using the same variable for the time being and if more gitlab projects get added then we can make the change.

**Comment by sara-02** [comment]
You are more than welcome to pick any approach and add the PR accordingly.

**Comment by NdibeRaymond** [comment]
the first approach seems more robust. will be submitting a PR

**Comment by heitorPB** [comment]
Should this issue be closed now?
