### ISSUE TITLE
Adding Flutter in Projects 

### ISSUE THREAD

**Issue by mohak852** [firstcontributions/firstcontributions.github.io#123]
Adding flutter for Android and ios app development
🐞 **Problem**

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

*   Comment below about what you've started working on.
*   Add, commit, push your changes.
*   Submit a pull request and add this in comments - `Addresses #<put issue number here>`
*   Ask for a review in comments section of pull request.
*   Celebrate your contribution to this project. 🎉

**Comment by TomerPacific** [comment]
I can take this on, if no one has any objection.

**Comment by mohak852** [comment]
I have already filed a PR and waiting for their responce

**Comment by mohak852** [comment]
any update @sara-02 on this

**Comment by TomerPacific** [comment]
@mohak852  - I would suggest you link to your PR here.

**Comment by sara-02** [comment]
@mohak852 there are review comments on your PR, kindly look into them, and after that we can merge them :)
