### ISSUE TITLE
Fix Images on List of Project List

### ISSUE THREAD

**Issue by imjoseangel** [firstcontributions/firstcontributions.github.io#136]
🐞 **Problem**

Some project images under the home page doesn't exist hence doesn't load properly

🎯 **Goal**

Fix broken links to load proper images

💡 **Possible solutions**

Fix on [listofprjeclistOfProjects.js](https://github.com/firstcontributions/firstcontributions.github.io/blob/source/src/components/ProjectList/listOfProjects.js) file.

📋  **Steps to solve the problem**

*   Comment below about what you've started working on.
*   Add, commit, push your changes.
*   Submit a pull request and add this in comments - `Addresses #<put issue number here>`
*   Ask for a review in comments section of pull request.
*   Celebrate your contribution to this project. 🎉

**Comment by ValKiriann** [comment]
Detected images to fix: Hyper, Game of life, Gatsby.
I am going to fix it now 🥇
