### ISSUE TITLE
Update logo and repo link from systers to anitab-org

### ISSUE THREAD

**Issue by vj-codes** [firstcontributions/firstcontributions.github.io#139]
Systers has moved to https://github.com/anitab-org .
Update logo and repo link in Projects section

🐞 **Problem**
Unaccurate logo and link

🎯 **Goal**
To keep this repo up to date fix the problem mentioned

**Comment by vj-codes** [comment]
@sara-02 I would like to work on this .Thanks!

**Comment by Roshanjossey** [comment]
@vj-codes, Sure, go ahead.

**Comment by HADES-01** [comment]
Is this issue still open ???

**Comment by sachin-duhan26** [comment]
@Roshanjossey considering no significant progress for 18 days, I would like to work on this issue.
I have already collected the updated links and logos to various projects that are missing on https://firstcontributions.github.io

**Comment by vj-codes** [comment]
@sachin-duhan26 hey I created a PR and it was merged too, forgot to close this
