### ISSUE TITLE
Broken link after clicking the Slack button

### ISSUE THREAD

**Issue by vj-codes** [firstcontributions/firstcontributions.github.io#140]
After I click the slack button , I get an error as 
```
This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.
```

🐞 **Problem**
Slack channel links expire after a certain amount of time . 

🎯 **Goal**
Update the current invite link

**Comment by Roshanjossey** [comment]
@vj-codes , please refer to https://github.com/firstcontributions/first-contributions/issues/30565
