### ISSUE TITLE
Add projects to project list 2020

### ISSUE THREAD

**Issue by aryasoni98** [firstcontributions/firstcontributions.github.io#144]
🐞 **Problem**

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

*   Comment below about what you've started working on.
*   Add, commit, push your changes.
*   Submit a pull request and add this in comments - `Addresses #<put issue number here>`
*   Ask for a review in comments section of pull request.
*   Celebrate your contribution to this project. 🎉

**Comment by Roshanjossey** [comment]
@aryasoni98, do we need another issue for the same thing https://github.com/firstcontributions/firstcontributions.github.io/issues/1 is doing?

 - https://github.com/firstcontributions/firstcontributions.github.io/issues/1 is still open.
 - It has a detailed description on how to handle the issue
 - It has pull requests linked to it that could help anybody looking for reference.
