### ISSUE TITLE
Fix width (and maybe height) of cards

### ISSUE THREAD

**Issue by CarlosUvaSilva** [firstcontributions/firstcontributions.github.io#15]
Cards are not full width in some cases and heigth is different depending on number of tags or description length.
🐞 **Problem**
Full width for all cards and maybe fixed height. Need to test this last enhancement.
🎯 **Goal**
Looks nicer when all the cards have same size

**Comment by CarlosUvaSilva** [comment]
I'm working on this one for Hacktober Fest

**Comment by CarlosUvaSilva** [comment]
Can you give me permissions to write to a new branch? Would like to create a PR

**Comment by Roshanjossey** [comment]
@CarlosUvaSilva, fork this project, create a branch there. Push to it and submit a pull request.

Read this to learn more about it https://github.com/firstcontributions/first-contributions/blob/master/README.md

Also I didn't quite understand what you're trying to achieve. Could you please share screenshots/ proposed design?

**Comment by CarlosUvaSilva** [comment]
I'm not at home atm, I'll submit the PR when I get there.
what I'm trying to fix is the difference in width inside the card. I believe this is due to the fact that the image's width is different between cards

![screen shot 2018-10-03 at 14 12 23](https://user-images.githubusercontent.com/6827956/46412414-6dca9100-c716-11e8-80ca-9004a7715ba7.png)

**Comment by Roshanjossey** [comment]
@CarlosUvaSilva, got it. I hadn't checked this is smaller screens.

Please take your time. No need to hurry.

**Comment by sara-02** [comment]
@Rohit777 @CarlosUvaSilva is this issue fixed?
