### ISSUE TITLE
[ UPDATE ] invalid or missing logos💡

### ISSUE THREAD

**Issue by sachin-duhan26** [firstcontributions/firstcontributions.github.io#153]
I recently visited [here](https://firstcontributions.github.io/) and found that many logos ( the list is given below) are either removed by the respective owners or image links are outdated.

🐞 **Problem**
- Invlid logo URL used in 
```
src/components/ProjectList/listOfProjects.js
```
**The list is as follows**
- ifme [ Line No. - 464 ]
- Game of Life [ Line No. 660 ]
- Light Table [ Line No. 541 ]

🎯 **Goal**

- Updated logo will have a better UI/UX and instill a professional outlook.

💡 **Possible solutions**

- update the list of logos at given lines numbers

**Comment by sara-02** [comment]
@sachin-duhan26 Thanks for reporting this.

**Comment by sachin-duhan26** [comment]
@sara-02 can you assign this to me?
I would love to correct this...
