### ISSUE TITLE
Adding Hacktoberfest Tags to Facebook share

### ISSUE THREAD

**Issue by Darkpingouin** [firstcontributions/firstcontributions.github.io#19]
Adding tags to facebook share to have more visibility (same as #13 but for Facebook share)

🎯 **Goal**
Reach out to more people who follows hacktoberfest tag on facebook.

💡 **Possible solutions**
Change the link in https://github.com/firstcontributions/firstcontributions.github.io/blob/source/src/components/SocialShare/Facebook.jsx

📋  **Steps to solve the problem**

*   Comment below about what you've started working on.
*   Add, commit, push your changes.
*   Submit a pull request and add this in comments - `Addresses #<put issue number here>`
*   Ask for a review in comments section of pull request.
*   Celebrate your contribution to this project. 🎉

**Comment by Darkpingouin** [comment]
I'm working on it

**Comment by sara-02** [comment]
Fixed in #20
