### ISSUE TITLE
Errors with the logo picture links

### ISSUE THREAD

**Issue by wordssaysalot** [firstcontributions/firstcontributions.github.io#196]
🐞 **Problem**
The React, React Native, Gatsby, and Navy Linux logos are missing.
<hr>

![1](https://user-images.githubusercontent.com/56651899/121823566-adb5e480-ccc3-11eb-9be1-d5b200cba13e.jpg)

![2](https://user-images.githubusercontent.com/56651899/121823567-af7fa800-ccc3-11eb-903b-dba8376942d0.jpg)

**Comment by Beatrix-droid** [comment]
May I please try to work on this? I am a newcomer to github, and would like to try and fix this as my first issue ever
