### ISSUE TITLE
Add an issue template

### ISSUE THREAD

**Issue by Roshanjossey** [firstcontributions/firstcontributions.github.io#2]
We can have the same issue template that we use in first-contributions

https://raw.githubusercontent.com/firstcontributions/first-contributions/master/.github/ISSUE_TEMPLATE.md

**Comment by sourabh1031** [comment]
@Roshanjossey i would like to work on this.can you please tell what is expected from me

**Comment by Roshanjossey** [comment]
@sourabh1031, create a file named ISSUE_TEMPLATE.md in this project. Use the same text as in the link shared above.

**Comment by sara-02** [comment]
Fixed and merged in #6
