### ISSUE TITLE
Card Header Image Link Broken 

### ISSUE THREAD

**Issue by ding-09** [firstcontributions/firstcontributions.github.io#225]
🐞 **Problem**

The image link for the React Native card is broken. 

🎯 **Goal**

Fix it by replacing it with a working image URL 

💡 **Possible solutions**

📋  **Steps to solve the problem**

*   Comment below about what you've started working on.
*   Add, commit, push your changes.
*   Submit a pull request and add this in comments - `Addresses #<put issue number here>`
*   Ask for a review in comments section of pull request.
*   Celebrate your contribution to this project. 🎉

**Comment by lakshmi930** [comment]
Can I work on this issue? I notice there are a couple of other broken images too. I can do this together then.
