### ISSUE TITLE
logo image link is broken in Ruby Koans card

### ISSUE THREAD

**Issue by Rohit777** [firstcontributions/firstcontributions.github.io#25]
🐞 **Problem**
in Ruby koans card  logo image link is broken 

🎯 **Goal**
look nicer if the logo image is visible

**Comment by Rohit777** [comment]
I'm working on this one for Hacktober Fest

Can you give me permissions to write to a new branch? Would like to create a PR

**Comment by Roshanjossey** [comment]
You don't need write permissions to the repo to create PR. You fork it and create branches there. But I guess you've figured that out.

**Comment by Roshanjossey** [comment]
Fixed in #26
