### ISSUE TITLE
Redirect link

### ISSUE THREAD

**Issue by rufilboy** [firstcontributions/firstcontributions.github.io#255]
🐞 **Problem**

The "Get started" link

Reduce much time before redirecting
🎯 **Goal**

It takes much time before redirecting to the default branch

They'll have quick access to the github page
💡 **Possible solutions**

📋  **Steps to solve the problem**

*   Comment below about what you've started working on.
*   Add, commit, push your changes.
*   Submit a pull request and add this in comments - `Addresses #<put issue number here>`
*   Ask for a review in comments section of pull request.
*   Celebrate your contribution to this project. 🎉

**Comment by DeexithParand2k2** [comment]
Can I work on this issue

**Comment by Roshanjossey** [comment]
Fixed in #254, #255
