### ISSUE TITLE
Wrong image sources

### ISSUE THREAD

**Issue by Yarnacle** [firstcontributions/firstcontributions.github.io#284]
🐞 **Problem**

Some of the objects listed in ``src/components/ProjectList/listOfProjects.js`` have an incorrect image source.
For example, the CircuitVerse card on the website looks like this:
![CircuitVerse card](https://iili.io/HHJpbRe.png)

So far, I have noticed the following project cards with the same issue:
* aprenda-go-com-testes

🎯 **Goal**

Properly display projects cards

💡 **Possible solutions**

It seems the problem is caused by linking a GitHub page rather than an image.
For example, the CircuitVerse object in ``listOfProjects.js`` has its ``imageSrc`` property set to ``https://github.com/CircuitVerse/CircuitVerse/blob/master/app/assets/images/CircuitVerse.png``, which is a link to this:
![Github page of CircuitVerse logo](https://iili.io/HHdBQ0g.png)

A solution to this problem would be to replace the incorrect image sources with each image's ``raw.githubusercontent.com``  URL.

📋  **Steps to solve the problem**

*   Comment below about what you've started working on.
*   Add, commit, push your changes.
*   Submit a pull request and add this in comments - `Addresses #<put issue number here>`
*   Ask for a review in comments section of pull request.
*   Celebrate your contribution to this project. 🎉

**Comment by HrutikaBadgeri** [comment]
please assign me this issue

**Comment by Nitinkumar2905** [comment]
I'm trying make the URL correct of these images which is stated in the issue
