### ISSUE TITLE
CircuitVerse card does not load Image

### ISSUE THREAD

**Issue by ifeanyiHM** [firstcontributions/firstcontributions.github.io#299]
🐞 **Problem**
CircuitVerse card only displays the alt message and does not load Image

🎯 **Goal**
Improve UI by simply displaying image properly.

💡 **Possible solutions**
locate source folder in `src/components/ProjectList/listOfProjects.js` and update image.

**Comment by ifeanyiHM** [comment]
Update CircuitVerse Card Image #298

**Comment by Yarnacle** [comment]
I have already brought this up in #284

**Comment by ifeanyiHM** [comment]
> I have already brought this up in #284

alright i'll take it down now
