### ISSUE TITLE
Mixed passive/display <img> (src attribute)

### ISSUE THREAD

**Issue by estellerostan** [firstcontributions/firstcontributions.github.io#30]
Loading mixed (insecure) display content on a secure page shows the "Your connection to this site is not fully secured" (Chrome) / "Connection is not secure" (Firefox) message in the address bar.

🐞 **Problem**

The HTTP request to http://hoodiehq.github.io/hoodie-css/src/content_img/animals/low-profile-dog-3.png is the problem.

🎯 **Goal**

Reclaim the "Secure Connection" in the address bar.
And better safeguard from most sniffers and man-in-the-middle attacks.

💡 **Possible solutions**

Make the call to http**s**://hoodiehq.github.io/hoodie-css/src/content_img/animals/low-profile-dog-3.png instead of http://hoodiehq.github.io/hoodie-css/src/content_img/animals/low-profile-dog-3.png.

**Comment by estellerostan** [comment]
#27 fixes this issue but maybe it is better to create a separate PR?

**Comment by Roshanjossey** [comment]
@estellerostan, I've merged #27 now. I'm not sure why we need a separate PR now.

**Comment by estellerostan** [comment]
Thank you!
It's all good another PR is not useful.

**Comment by Roshanjossey** [comment]
Thank you again @estellerostan 🖖
