### ISSUE TITLE
Improve accessibility of the app

### ISSUE THREAD

**Issue by Roshanjossey** [firstcontributions/firstcontributions.github.io#346]
<img width="520" alt="Screenshot 2023-07-31 at 09 16 26" src="https://github.com/firstcontributions/firstcontributions.github.io/assets/8488446/8684b808-9c60-4341-bd97-d2769209a5c7">

🐞 **Problem**

Accessibility score of this app on lighthouse is 85 now. It would be good to make it more accessible.

🎯 **Goal**

More users can use this app.

💡 **Possible solutions**

Make necessary changes to improve accessiblity.

📋  **Steps to solve the problem**

*   Comment below about what you've started working on.
* 	 Run lighthouse from your developer console to see the metrics and possible solutions.
*   Add, commit, push your changes.
*   Submit a pull request and add this in comments - `Addresses #<put issue number here>`
*   Ask for a review in comments section of pull request.
*   Celebrate your contribution to this project. 🎉

**Comment by Mandy-cyber** [comment]
Commenting to say I have started working on this problem, starting with the form elements and links 🧚🏽‍♀️

**Comment by Roshanjossey** [comment]
Closing as this has been handled in #359.
