### ISSUE TITLE
By clicking "Go to Project" it should be open in new tab

### ISSUE THREAD

**Issue by Shubham7350** [firstcontributions/firstcontributions.github.io#351]
🐞 **Problem**

When I found the relevant project to contribute to or view it and I clicked on the "Go to Project" button it opens the same tab I lost the previous tab of First Contributions and it will be beneficial to open it in a new tab. Nobody is using mobile for development so it will be not much irritate on mobile too. But opening in the same tab will be much irritated.
🎯 **Goal**
Adding the HTML attribute which will open the project into the new tab.

![Screenshot 2023-02-07 154317](https://user-images.githubusercontent.com/90132010/217218091-0cb29643-7af9-4a90-a1f0-d659d6a979d9.png)

**Comment by Roshanjossey** [comment]
This is fixed now
