### ISSUE TITLE
Broken links in projects list

### ISSUE THREAD

**Issue by Esh07** [firstcontributions/firstcontributions.github.io#368]
🐞 **Problem**

Project list contains broken links that lead to a 404 page, possibly due to the repository being made private or deleted.

🎯 **Goal**

Please remove dead links - there is one project which has no link associates to it. Please follow the test link below to see which link is broken.

💡 **Possible solutions**

I'd tested the with Github APIs and here is list of projects with their respective status code - 404 need to resolve (red colour). 200 is success.
- Test https://jsfiddle.net/9m58a12u/356

📋  **Steps to solve the problem**

*   Comment below about what you've started working on.
*   Add, commit, push your changes.
*   Submit a pull request and add this in comments - `Addresses #<put issue number here>`
*   Ask for a review in comments section of pull request.
*   Celebrate your contribution to this project. 🎉

**Comment by thrila** [comment]
hi id lo0ve to work on this!!!!!

**Comment by thrila** [comment]
for the links that are broken do i point them out or remove the cards entirely??

**Comment by ShaikhAman01** [comment]
May I work on this @Esh07

**Comment by sarans-h** [comment]
is this fixed?
I am new please help me to contribute

**Comment by Esh07** [comment]
Thanks for your interest! 

I'm just a contributor, not the maintainer. Feel free to use this issue for progress updates and communication regarding your PR. When you open the PR, please link this issue to keep everything connected. 

Thanks!

**Comment by Roshanjossey** [comment]
Fixed
