### ISSUE TITLE
Add ifme to project list

### ISSUE THREAD

**Issue by Roshanjossey** [firstcontributions/firstcontributions.github.io#4]
Here's a link to beginner friendly issues in ifme https://github.com/ifmeorg/ifme/issues?q=is%3Aissue+is%3Aopen+label%3A%22beginner+friendly%22

Go through #1 to figure out how to go about doing this.

**Comment by achiv** [comment]
I would like to work on this

**Comment by IAMOTZ** [comment]
Hi @Roshanjossey 
I would like to claim this issue.

**Comment by IAMOTZ** [comment]
Hi @Roshanjossey 
I am okay with leaving this issue for another beginner.
Would love to get recommendations on projects that I can contribute to. I am a javascript engineer focused on the PERN(Postgres Express React Node) stack.
Thanks.

**Comment by Roshanjossey** [comment]
https://github.com/freeCodeCamp/mail-for-good/issues
https://github.com/TryGhost/Ghost/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
https://github.com/hoodiehq/hoodie/issues
https://github.com/probot/probot/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue+%F0%9F%8E%88%22

**Comment by Alumenium** [comment]
Hey @Roshanjossey, I would like to work on this issue.

**Comment by Roshanjossey** [comment]
@Alumenium, go ahead.

**Comment by Alumenium** [comment]
@Roshanjossey made a PR, please review.

**Comment by sara-02** [comment]
Merged in #7
