### ISSUE TITLE
Update social media references to replace Twitter with X

### ISSUE THREAD

**Issue by marknoble** [firstcontributions/firstcontributions.github.io#403]
🐞 **Problem**
The current project documentation and social media references are outdated and still point to Twitter. This can lead to confusion and misdirection for new contributors looking to connect with the project’s community or seek support.

🎯 **Goal**
The goal is to update all references to Twitter in the project’s documentation, website, and contribution guides with the new platform ‘X’. This will ensure that contributors have access to the latest and most accurate information. It’s important to maintain up-to-date resources to facilitate effective communication and community engagement.

💡 **Possible solutions**
One possible solution is to conduct a thorough review of all the documents and web pages associated with the project to identify any mentions of Twitter. Once identified, these can be systematically replaced with the correct references to ‘X’.

📋  **Steps to solve the problem**
* Comment below about what you’ve started working on.
* Review the project’s documentation and website for Twitter references.
* Replace all instances of Twitter with ‘X’.
* Add, commit, and push your changes to a new branch.
* Submit a pull request with the changes and include Addresses #<put issue number here> in the comments.
* Ask for a review in the comments section of the pull request.
* Celebrate your contribution to this project once the changes are merged. 🎉

**Comment by diamond-nicholas** [comment]
Hello i would like to jump on this issue. Can i proceed?

**Comment by marknoble** [comment]
There's already a pull request. I suppose you could review the pull request and provide feedback on it.
