### ISSUE TITLE
Some projects' description have misspelled words

### ISSUE THREAD

**Issue by 7H3XXX** [firstcontributions/firstcontributions.github.io#407]
🐞 **Problem**
While reading through the list of projects I noticed there are errors in some projects' description.
For example: advance instead of advanced

🎯 **Goal**
By fixing this, user won't have to make too much effort to know what a project is about.

**Comment by ijayhub** [comment]
still opened? assign me

**Comment by ekrishnachaitanya2004** [comment]
I would like to extend an invitation to individuals interested in contributing to my open-source website. Your participation and contributions will be greatly appreciated.
[**Link**](https://github.com/Snakes-n-Networks/Dev-blogs.git)
