### ISSUE TITLE
image loading issue

### ISSUE THREAD

**Issue by 16ratneshkumar** [firstcontributions/firstcontributions.github.io#410]
problem:
Some image on your website is not loading, maybe it is not on that path or something else.

**Comment by samyak-aditya** [comment]
Assign me this issue

**Comment by samyak-aditya** [comment]
> problem: Some image on your website is not loading, maybe it is not on that path or something else.

Assign me this issue

**Comment by 16ratneshkumar** [comment]
Assigned this issue

**Comment by samyak-aditya** [comment]
> Ready to merge, you can check

I am working on it
Have you already made the changes?

**Comment by 16ratneshkumar** [comment]
> > Ready to merge, you can check
> 
> I am working on it
> Have you already made the changes?

Ye I have done you can check in pull request

**Comment by 16ratneshkumar** [comment]
Please Response

**Comment by samyak-aditya** [comment]
Yes I have Checked it.
Everything Seems to be correct

**Comment by 16ratneshkumar** [comment]
Oky then any problem in merge.

**Comment by olamilly** [comment]
All changes complete. Ready to merge. https://github.com/firstcontributions/firstcontributions.github.io/pull/413

**Comment by nikhilchary129** [comment]
i did add new image URL found a new issue {a missing href} which i raised issue #416 
Ready to merge
