### ISSUE TITLE
 Title: Missing href Attribute in <a> Tag for Project Card->{aprenda-go-com-testes}

### ISSUE THREAD

**Issue by nikhilchary129** [firstcontributions/firstcontributions.github.io#416]
### 🐞 **Problem**

The `<a>` tag in the project card component is missing an `href` attribute. This omission prevents the card from functioning as a clickable link, thus not directing users to the intended project URL.
### **image**
![image](https://github.com/user-attachments/assets/e159a306-be44-4442-b819-777757e1d5e6)

### **current code**
```
<a class="Card-Real-Link" target="blank">
  <div class="Card-Header">
    <img class="Project-Logo" alt="the framework or language that the project is built upon" src="https://github.com/larien/aprenda-go-com-testes/blob/main/.gitbook/assets/red-green-blue-gophers-smaller.png">
    <p class="Card-Title">aprenda-go-com-testes</p>
  </div>
  <div class="Card-Body">
    <div class="Card-Tag">
      <div><p>go</p></div>
    </div>
    <div class="Card-Description">
      <p>learn easily and quickly</p>
    </div>
  </div>
  <div class="Card-Link">Go to Project</div>
</a>
```
### 🎯 **Goal**

The goal is to add the `href` attribute to the `<a>` tag so that the project card properly links to the project's URL. This enhancement will make the card functional, allowing users to navigate to the project by clicking on it. It is essential for improving user experience and ensuring that the card performs its intended purpose.

### 💡 **Possible Solutions**

1. **Add the `href` Attribute**: Include the `href` attribute in the `<a>` tag with the appropriate project URL.
   ```html
   <a class="Card-Real-Link" href="https://github.com/larien/aprenda-go-com-testes" target="_blank">
   ```
   Ensure the `target` attribute is correctly set to `_blank` to open the link in a new tab.

2. **Update Documentation**: Verify that any related documentation or references are updated to reflect the change.

### 📋 **Steps to Solve the Problem**

1. Comment below about what you've started working on.
2. Add the `href` attribute to the `<a>` tag in the code.
3. Commit your changes with a clear message.
4. Push your changes to the repository.
5. Submit a pull request and add this comment: `Addresses #<put issue number here>`.
6. Ask for a review in the comments section of the pull request.
7. Celebrate your contribution to this project! 🎉

**Comment by BRP-08** [comment]
Hey @nikhilchary129 if this issue is unassigned I would like to work on it

**Comment by nikhilchary129** [comment]
sure go ahead
@BRP-08

**Comment by HimalayaSingh3** [comment]
Hello! I'd like to work on this issue!

**Comment by Joby-John** [comment]
Hi, if this is still open I'd like to resolve it

**Comment by Famzy077** [comment]
Hey I will like to work on this project if it is still open
