### ISSUE TITLE
aprenda-go-com-testes card does not have a language image

### ISSUE THREAD

**Issue by Joby-John** [firstcontributions/firstcontributions.github.io#433]
🐞 **Problem**
The card of aprenda-go-com-testes, does not load a language image (the language of the repo).

🎯 **Goal**
This can enhance the user experience of the website particularly of the card.

💡 **Possible solutions**
<!--- Image link is present there in listOfProjects.js, modify it with a working image link to solve->

📋  **Steps to solve the problem**

*   Comment below about what you've started working on.
*   Add, commit, push your changes.
*   Submit a pull request and add this in comments - `Addresses #<put issue number here>`
*   Ask for a review in comments section of pull request.
*   Celebrate your contribution to this project. 🎉

**Comment by mihir1313** [comment]
Please assign me the task.
