### ISSUE TITLE
Missed projectLink

### ISSUE THREAD

**Issue by savvygentleman** [firstcontributions/firstcontributions.github.io#437]
Can't access project url

🐞 **Problem**
There's no projectLink in aprenda-go-com-testes

🎯 **Goal**
They can't see project of aprenda-go-com-testes

💡 **Possible solutions**
Add projectLink in listOfProjects

**Comment by Srikanth9793** [comment]
@Roshanjossey Please review this https://github.com/firstcontributions/firstcontributions.github.io/pull/449

Thanks
