### ISSUE TITLE
Sorting of projects always presents the same projects presently

### ISSUE THREAD

**Issue by jancborchardt** [firstcontributions/firstcontributions.github.io#47]
🐞 **Problem**
Currently every time you open the page, the first projects everyone sees are React, React Native and Exercism. As people most probably browse and don’t search for a specific project, that gives projects which were added later (or which are smaller and less known than React) less exposure.

🎯 **Goal**
The goal is to present every project on an equal footing. And to also show the variety of projects on the platform.

💡 **Possible solutions**
To achieve that, every time the page is loaded the order could be randomized.

What do you think @Roshanjossey @sara-02? :)

**Comment by gopkumr** [comment]
I like the suggestion, in case @Roshanjossey likes it too, i have PR implemented this.

**Comment by jancborchardt** [comment]
@gopkumr good stuff! Maybe just open a pull request for it, then everyone can test and review. :)

**Comment by gopkumr** [comment]
@jancborchardt I have already opened a pull request for the change. PR #50 Randomised Sorting of cards is  with their changes.
