### ISSUE TITLE
Add opensourcedesign to project list

### ISSUE THREAD

**Issue by Roshanjossey** [firstcontributions/firstcontributions.github.io#5]
Here's a link to beginner level issues in opensourcedesign https://github.com/opensourcedesign/opensourcedesign.github.io/issues?q=is%3Aissue+is%3Aopen+label%3A%22starter+issue%22

You can figure out how to do this by going to #1

**Comment by IAMOTZ** [comment]
Hi @Roshanjossey 
I would like to claim this issue.

**Comment by Roshanjossey** [comment]
@IAMOTZ, Sure. go ahead.

**Comment by IAMOTZ** [comment]
Just raised a PR for this: https://github.com/firstcontributions/firstcontributions.github.io/pull/7

**Comment by Roshanjossey** [comment]
Looks good @IAMOTZ. Thank you for making this change.

**Comment by sara-02** [comment]
Fixed and merged in #7
