### ISSUE TITLE
Broken Teammates image

### ISSUE THREAD

**Issue by eduayme** [firstcontributions/firstcontributions.github.io#64]
🐞 **Problem**
The Teammates image is broken.
<img width="1417" alt="Screenshot 2019-09-30 at 18 09 29" src="https://user-images.githubusercontent.com/26260104/65896448-8f07a100-e3ad-11e9-93c2-fa46d9b53486.png">

🎯 **Goal**
The Teammates card must have a valid logo.

💡 **Possible solutions**
Get a new url image and change it for the current one.

📋  **Steps to solve the problem**
- Get a valid Teammates image as a logo.
- Change the current url for the new image url.

**Comment by Apoorva-13** [comment]
Hey, I would like to take this up

**Comment by sara-02** [comment]
@Apoorva-13 sure, go ahead.

**Comment by Apoorva-13** [comment]
Hey 
would this logo do ?? 
[(https://teammatesv4.appspot.com/images/teammateslogo.png)]

**Comment by sara-02** [comment]
@Apoorva-13 Yes, this is the right place to add.
