### ISSUE TITLE
Add Conda Project to the project list

### ISSUE THREAD

**Issue by sara-02** [firstcontributions/firstcontributions.github.io#67]
As a followup on the PR https://github.com/firstcontributions/first-contributions/pull/19582, we can add the Conda project to the list of projects.
* Possible tags like `ML`, `Python`, `Builds` , `package manager` etc.
* Link to the github org: https://github.com/conda
* Link to logo: https://conda.io/en/latest/_images/conda_logo.svg

**Comment by Apoorva-13** [comment]
hey, can i work on this?

**Comment by sara-02** [comment]
@Apoorva-13 sure.
