### ISSUE TITLE
Fix Casing Inconsistency In Tags.

### ISSUE THREAD

**Issue by sara-02** [firstcontributions/firstcontributions.github.io#71]
Some of the tags are in Capital letters, some in small. I suggest we Capitalise the tags[the first letter of each word in tagset] and use make them uniform.
 
🎯 **Goal**

- [ ] Fix the upper/lower case inconsistency in tags.

- [ ] Also, add a comment at the EOF which states the casing format to be used for tags. It will be useful for future contributors.

- [ ] Add `text-transform: capitalize` to the tag CSS

**Files to change**
* https://github.com/firstcontributions/firstcontributions.github.io/blob/source/src/components/ProjectList/listOfProjects.js
* https://github.com/firstcontributions/firstcontributions.github.io/blob/source/src/components/ProjectList/css/project-cards.css#L87

**Comment by vivek1996** [comment]
Hi @sara-02 , I would like to contribute for this issue. May I know where the issue is. Please point out any one so it would be easy. Thank You.

**Comment by sara-02** [comment]
> Hi @sara-02 , I would like to contribute for this issue. May I know where the issue is. Please point out any one so it would be easy. Thank You.

@vivek1996 this is the file that needs fixing: https://github.com/firstcontributions/firstcontributions.github.io/blob/source/src/components/ProjectList/listOfProjects.js

**Comment by andreaslorozco** [comment]
An additional idea could be adding `text-transform: capitalize;` to the tag CSS (maybe as a fallback?)

**Comment by sara-02** [comment]
> An additional idea could be adding `text-transform: capitalize;` to the tag CSS (maybe as a fallback?)

@andreaslorozco I am assuming this is the file where we add? https://github.com/firstcontributions/firstcontributions.github.io/blob/source/src/App.css

**Comment by andreaslorozco** [comment]
This should be a better place since there's CSS there that's already targeting each tag: https://github.com/firstcontributions/firstcontributions.github.io/blob/source/src/components/ProjectList/css/project-cards.css#L87

**Comment by sara-02** [comment]
> This should be a better place since there's CSS there that's already targeting each tag: https://github.com/firstcontributions/firstcontributions.github.io/blob/source/src/components/ProjectList/css/project-cards.css#L87

Got it.

**Comment by sara-02** [comment]
@vivek1996 as per the discussion above, I have updated the issue.
