### ISSUE TITLE
CONTRIBUTING.md file lacking instructions

### ISSUE THREAD

**Issue by R-Ligier** [firstcontributions/firstcontributions.github.io#78]
I was following the CONTRIBUTING.md file to be able to make a contribution to the project. When I got to the "Running the Project" section and ran the command "yarn install", after following the previous steps, it did not work and said "command not found." This is obviously because I need to have yarn installed before I can run this command. 

🐞 **Problem**

I would like to propose adding a line stating that the user must have yarn installed and maybe some links on where they can do that.

🎯 **Goal**

It's important to me because as a first timer I encountered this issue but knew how I would solve it. However, folks who are still new to coding/contributing might not know this and feel stuck.

It will let them know that they need to have yarn installed before running the command.

💡 **Possible solutions**

📋  **Steps to solve the problem**

*   Comment below about what you've started working on.
*   Add, commit, push your changes.
*   Submit a pull request and add this in comments - `Addresses #<put issue number here>`
*   Ask for a review in comments section of pull request.
*   Celebrate your contribution to this project. 🎉

**Comment by Roshanjossey** [comment]
Hi @R-Ligier , thank you for opening this issue.

There are some pre-requirements to run this project (node, yarn, etc). It'd be nice to have a pre-requirements section with link to install pages of these. 

Would you like to work on this?

**Comment by R-Ligier** [comment]
Hi @Roshanjossey - sure, i'd love to work on this.

**Comment by Roshanjossey** [comment]
Cool. Go ahead.

**Comment by R-Ligier** [comment]
Hi @Roshanjossey, I am not sure what to do about updating the CONTRIBUTING.md file. Im not sure if the issues I ran into are issues everyone may run into or not. I dont want to change anything if for the majority it does work. On my end, I had to remove the package-lock.json file and also used npm start instead of the yarn command.

Perhaps, I can add a line stating that the user must have node.js installed before running the commands?

Here are the details:

1. I ran **yarn install** and received an error stating that the command is not found. To solve this issue, i installed yarn and made sure I had the latest version. The command again did not work. After trying multiple things I found on forums, I gave up. 

2. I looked at the README file and noticed in the table of contents the npm "Available scripts". I decided to give **npm start** a try to see if that works and once again encountered errors. Here are the errors:

`npm ERR! code ELIFECYCLE` 
`npm ERR! syscall spawn`
`npm ERR! file sh`
`npm ERR! errno ENOENT`
`...........`

After some research, I found this [solution](https://stackoverflow.com/questions/42308879/npm-err-code-elifecycle) that ended up working for me: 
`Step 1: $ npm cache clean --force`
`Step 2: Delete node_modules by $ rm -rf node_modules folder or delete it manually by going into the directory and right-click > delete / move to trash. Also, delete package-lock.json file too.`
`Step 3: npm install`
`To start again, $ npm start`

Please let me know what I should do from here.

Thanks!

**Comment by Roshanjossey** [comment]
Hi @R-Ligier, we'd like to stick with yarn as we had good experience with it so far.

Could you share the errors you're getting when you use yarn? I can help you there.

**Comment by R-Ligier** [comment]
I actually was able to figure it out ... For some reason when I tried installing yarn via Homebrew `brew install yarn` it gave an error. But when I ran this script `curl -o- -L https://yarnpkg.com/install.sh | bash` it worked!

I will add a link to the CONTRIBUTING document on where users can install yarn.

**Comment by R-Ligier** [comment]
Actually nvm :( I got this error. 

![yarn error](https://user-images.githubusercontent.com/25729928/67789688-c6b84600-fa4a-11e9-8bc8-0516f585303f.png)

**Comment by Roshanjossey** [comment]
First you have to run `yarn` or `yarn install` to install dependencies.

If you run in to problems there, delete `node_modules` and `package.lock.json` and try again.

We're bound to run into problems if we use multiple package managers. Then, there's no single source of truth. 

@sara-02 , we have to make sure that we don't merge changes that adds `package.lock.json`

**Comment by sara-02** [comment]
Ok. So what do we do, add `package.lock.json` to gitignore?

**Comment by Roshanjossey** [comment]
Yeah, that's a good plan

**Comment by R-Ligier** [comment]
@Roshanjossey when i remove `node_modules` and `package.lock.json` it works fine. 

In terms of solving this issue, what is the best way to let users know to do this if they run into an error? Should I just add a line that suggests to users to remove those files?

**Comment by Roshanjossey** [comment]
`package.lock.json` is the one that's causing problems with yarn. 

As @sara-02 suggested above, could you remove it and add it to `.gitignore`? 

You could add a line suggesting contributors who runs in to problems with dependencies to try removing `node_modules`

**Comment by R-Ligier** [comment]
Submitted a pull request.

**Comment by Roshanjossey** [comment]
@sara-02, shall we close this? I've removed `package-lock.json`. Let's revisit `yarn` vs `npm` if the community asks for it.

[Unrelated]: @R-Ligier dislikes jury duty but thinks that you're a pretty nice maintainer https://hunter-college-ossd-fall-2019.github.io/R-Ligier-weekly/week08/
