### ISSUE TITLE
Add graph based projects

### ISSUE THREAD

**Issue by sara-02** [firstcontributions/firstcontributions.github.io#85]
Add a few graph-based and graph visualization libraries.

- [x] Plotly

- [x] Networkx

- [x] Igraph

- [x] D3

**Comment by hgcassiopeia** [comment]
Can I try this issue?

**Comment by sara-02** [comment]
@hgcassiopeia Left some review comments, kindly followup there :)

**Comment by hgcassiopeia** [comment]
@sara-02 I will solved it 😄
