### ISSUE TITLE
Add YouTube channel link

### ISSUE THREAD

**Issue by Roshanjossey** [firstcontributions/firstcontributions.github.io#96]
🎯 **Goal**
Get more people to know about the YouTube channel

💡 **Possible solutions**
Add a [link to our Youtube channel](https://www.youtube.com/channel/UCMXNFxCvyH5LhUwEcmY8qGQ) `https://www.youtube.com/channel/UCMXNFxCvyH5LhUwEcmY8qGQ` in our web app.
We have navigation links in `src/components/Navbar/Navbar.jsx`.

It could be placed between Slack and twitter link.

📋  **Steps to solve the problem**

*   Comment below about what you've started working on.
*   Add, commit, push your changes.
*   Submit a pull request and add this in comments - `Addresses #<put issue number here>`
*   Ask for a review in comments section of pull request.
*   Celebrate your contribution to this project. 🎉

**Comment by Salmankhancodes** [comment]
can i solve this issue...and if yes i wanna know do i have to create new branch ?

**Comment by sara-02** [comment]
> can i solve this issue...and if yes i wanna know do i have to create new branch ?

I guess you were able to figure out how to create a new branch.

**Comment by Salmankhancodes** [comment]
> > can i solve this issue...and if yes i wanna know do i have to create new branch ?
> 
> I guess you were able to figure out how to create a new branch.

yess😊

**Comment by Roshanjossey** [comment]
Thank you for taking care of this @Salmankhancodes , @sara-02 

It's live now
