### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by Roshanjossey** [firstcontributions/firstcontributions.github.io#98]
Have content in the Readme to suit the project better

🐞 **Problem**
Currently, we have default Readme generated by `Create React App`. As much as this is useful, we can have a Readme that's tailored to this project that helps contributors and users better.

🎯 **Goal**
Have a cool , awesome Readme

💡 **Possible solutions**
Let's have a discussion about what makes a Readme effective. What we need for this project etc

📋  **Steps to solve the problem**

 * Comment down below the things you'd like to have (or be removed) in the Readme.
 * Vote on things you like or those you find useful
 * Submit pull requests to address the things we decide on.

**Comment by Roshanjossey** [comment]
Some of the Readmes I like a lot

https://github.com/gitpoint/git-point/blob/master/README.md
https://github.com/ryanoasis/nerd-fonts/blob/master/readme.md
https://github.com/thelounge/thelounge/blob/master/README.md


And links to bunch of others https://github.com/matiassingers/awesome-readme

**Comment by marianovarela** [comment]
Hi, I'd like to help out and propose a new readme

**Comment by sara-02** [comment]
@marianovarela awesome, you can share some of the ideas on the issue here or create a Work in Progress [WIP] PR with your proposed idea and tag us to review.

**Comment by marianovarela** [comment]
Is it desirable that the heading 
"This project was bootstrapped with Create React App.
Below you will find some information on how to perform common tasks.
You can find the most recent version of this guide here." 
appears in the README or can we remove it?

**Comment by Roshanjossey** [comment]
I'd say we rather remove it. 

1. This information is only relevant to updating react part of the code. Most pull requests we get is not about this.
2. It's better to link to the documentation of Create React app here. They'll have the up-to-date documentation.
3. For running the app locally, the contributor need not know about CRA. 
    `yarn`
    `yarn start` 
is enough.
